Dayol-Studio/Dayol-iOS

Dayol-iOS/UI/Common/DiaryCover/DairyView.swift, Dayol-iOS/UI/Common/DiaryCover/DiaryCoverView.swift, Dayol-iOS/UI/Common/DiaryCover/DiaryLockerView.swift, Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift, Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift, Dayol-iOS/UI/Home/Main/ViewController/HomeViewController.swift, Dayol-iOS/UI/Password/View/PasswordTitleView.swift, Dayol-iOS/UI/Password/View/PasswordViewController+Bind.swift, Dayol-iOS/UI/Password/View/PasswordViewController.swift
- DiaryView: HomeView와 PasswordView 연동
- @Sungmin-Joo 가 생성한 DiaryListModel로 HomeView <-> PasswordView 상호 소통
- 이후의 Step 구현 필요
- Password 통과 이후 HomeView에서의 처리
=> [Add] DiaryView, HomeView, PasswordView Integration

Podfile
- 캘린더 관련 속지를 위한 라이브러리 추가
`pod 'FSCalendar', '2.8.2'`
=> [Pod] Add FsCalendar 2.8.2

Dayol-iOS/UI/DiaryPaper/View/DiaryPaperEmptyView.swift
- 아이폰의 경우 EmptyView Width가 화면보다 크게 잡히는 문제 Fix
- 아이폰 전용 Constraint  추가
=> [Modify] EmptyView Fix For IPhone

.github/workflows/swift.yml
=> [Update] swift.yml

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/Extension/UIView+Extension.swift, Dayol-iOS/UI/Common/Toast/DYToastView.swift
- [Add] DYToast 정의
- [Add] UIView+Extension으로 토스트뷰를 쉽게 노출할 수 있도록 구현  
``` swift   
someview.showToast(text: "안녕하세요.\n토스트에욧", bottomMargin: 16.0 + 55.0)
```  
+gif프레임이 좀 밀려서 노출될때 애니메이션이 없는 것 같지만 fadeout, fadein 둘 다 같은 값을 사용했습니다
=> [Add] DYToast 정의

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/Localization/en.lproj/Localizable.strings, Dayol-iOS/Localization/ko.lproj/Localizable.strings, Dayol-iOS/UI/Settings/Model/SettingsModel.swift, Dayol-iOS/UI/Settings/ViewController/SettingsDetailViewController.swift, Dayol-iOS/UI/Settings/ViewController/SettingsViewController.swift, Dayol-iOS/UI/Settings/ViewModel/SettingsViewModel.swift
세팅 설정 -> 세부 설정 화면 진입 점 구현했습니다.  
추후 각 세부사항 contentView를 정의해서 끼워넣는 형식으로 작업을 이어 갈 예정이며, 
pr 규모가 커질 것 같아 베이스 작업부터 올렸습니다.
=> [Add] SettingDetailViewController 구현

Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+bind.swift
=> [Mod] Setting화면 진입 시 패드일 경우 컨텐츠 사이즈를 가이드에 맞게 수정

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/UI/DiaryPaper/Papers/FourPaper.swift
- 가이드에서 FourPage 라는 명칭을 사용하길래 일단 enum 값이나 클래스명이나 FourPage로 통일했습니다.  
- 일단 간단한게 속지만 그려놓은 상태이고 이 브랜치를 기점으로 드로잉 기능 이식 작업을 진행할 예정입니다.
=> [Add] 가로, 세로 줄이 있는 속지 구현

Dayol-iOS/Localization/en.lproj/Localizable.strings, Dayol-iOS/Localization/ko.lproj/Localizable.strings
localization 파일 수정했습니다. 임시로 앱 내 글자들이 안보일 것 같은데.. 이건 따로 작업해서 pr올리는게 나을 것 같아서 요 수정사항만 먼저 올립니다.
=> [#56][Mod] localization 파일 수정

Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift, Dayol-iOS/UI/DiaryPaperModal/PaperList/View/PaperListContentView.swift, Dayol-iOS/UI/DiaryPaperModal/PaperList/ViewModel/PaperListContentViewModel.swift, Dayol-iOS/UI/DiaryPaperModal/ViewController/PaperModalViewController.swift
- Dairy Paper List 테스트 데이터와 연동했습니다
- 데이터 타입은 언제든지 바뀔 수 있으며
- DB 정의 후 유연하게 대처할수 있도록 shared된 TestData로 처리했습니다.
- Papers를 계속해서 넘기는 것이 아니라 Diary 하나의 데이터를 넘기면 각자의 역할에 맞게 가공하여 넘겨주는 것이 맞지만
- 개인적인 의도이므로 DB 정의 후 재정의 하는게 맞는것 같습니다.
- 다이어리 첫 화면은 @Sungmin-Joo 의 다이어리 속지 작업이 끝난 후 진행하겠습니다.
=> [Add] Apply Diary Paper List Test Data

Dayol-iOS/TestData/DiaryPageListTestData.swift, Dayol-iOS/UI/DiaryPaper/ViewController/DiaryPaperViewController.swift
- Paper가 하나도 없을시에 보여지는 EmptyView를 적용했습니다.
=> [Add] Apply EmptyPaper

Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift, Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift
막간을 이용해 메인 다이어리 페이징 느낌을 살려봤습니다.
=> [ADD] 컬렉션 뷰 페이징 구현

Dayol-iOS/UI/Common/DYNavigationController/DYNavigationEditableTitle.swift, Dayol-iOS/UI/Common/DiaryCover/DairyView.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
- 컬러 변경 애니메이션 적용  
- 타이틀 변경사항 저장
- 키보드 핸들링
=> [Mod] 다이어리 생성화면 디테일 기능 구현  

Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/PaperPresentView.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Viewer/DiaryPaperViewController.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Viewer/DiaryPaperViewerViewController.swift
- PaperScroll 페이징 추가
- StickerContentView, DrawingContentView 추가
=> [Add] ScrollView Paging, StrickerContent, DrawingContents

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/UI/Common/DYModalViewController/DYModalViewController.swift, Dayol-iOS/UI/Common/DiaryCover/DairyView.swift, Dayol-iOS/UI/Common/Draw/DYDrawTool.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Color/ColorSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Erase/EraseSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilTypeSettingView.swift, Dayol-iOS/UI/Common/ViewController/DYDrawableViewController.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+DYDrawableDelegate.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift
- 다이어리 편집화면에 펜슬 기능을 연동  
- ColorSettingView는 스펙이 변경되어서 따로 상세 작업 진행할 예정입니다. 기능 구현만 해두었습니다.  
회의때 화면공유로 보여드렸기에 생략하겠습니다..
=> [Add] 다이어리 편집 화면에 펜슬 기능 연동  

Dayol-iOS/UI/Common/View/ToolBarContent/Color/ColorPicker/ColorPicker.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Color/ColorPickerContentView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Color/ColorSettingPaletteView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Color/ColorSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilAlphaSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilSettingView.swift, Dayol-iOS/UI/Common/ViewController/DYDrawableViewController.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+DYDrawableDelegate.swift, Dayol-iOS/UI/DiaryPaper/InputAccessaryView/DYKeyboardInputAccessoryView.swift
- 컬러피커 가이드 수정사항 반영  
- 텍스트필드용 컬러피커 구현
=> 컬러피커 스펙 수정사항 반영 및 키보드 액세서리 뷰에서 컬러피커 이동하는 씬 구현

Dayol-iOS/UI/DiaryEdit/View/DiaryEditCoverView.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+DYDrawableDelegate.swift
지난 번 리뷰에서 팬 기능 사용시에는 두손가락으로 스크롤이 가능하도록 요청해주셔서 반영했습니다.
=> [Add] 드로잉 기능 사용할때는 두 손가락 드래그 기능 추가

Dayol-iOS/UI/Common/DYModalViewController/DYModalViewController.swift, Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/View/MonthlyCalendarView.swift, Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/ViewModel/MonthlyCalendarViewModel.swift, Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/PaperPresentView.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Viewer/DiaryPaperViewController.swift
- 페이퍼 사이즈가 맞지 않던 문제 수정(코드 누락, 왜?)
- 특정 월의 날짜가 맞지않던 문제 수정(1일이 토요일인 경우)
- 헤더에 월이 표시되지 않던 문제 수정
- 페이퍼 add하는 과정이 맞지 않던 문제 수정(dismissHandler동작 방식 변경)
=> fix Some Error

Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilAlphaInfoView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilAlphaSettingView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/Pencil/PencilSettingView.swift
펜 설정 파레트에서 알파 값 조절 시 펜에 반영되도록 연동해두었습니다.
=> [Add] 펜 설정 알파 값 적용

.github/workflows/swift.yml, Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS.xcodeproj/xcshareddata/xcschemes/Dayol Beta.xcscheme, Dayol-iOS.xcodeproj/xcshareddata/xcschemes/Dayol Prod.xcscheme, Dayol-iOS/Config.swift, Dayol-iOS/Utils/Logging.swift, SupportingFiles/Config/Beta.xcconfig, SupportingFiles/Config/Product.xcconfig, SupportingFiles/DAYOL.entitlements, SupportingFiles/DAYOLBeta.entitlements, SupportingFiles/Info.plist
=> Create Config file

Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+MoreMenu.swift
- 비밀번호 생성/제거 후 다이어리 썸네일 업데이트 필요  
- 비밀번호 로직 수정 후 같이 수정 필요
=> 홈 다이어리 리스트 -> 다이어리 비밀번호 생성/삭제 이벤트 연동

Dayol-iOS/UI/DiaryPaper/ViewController/Viewer/DiaryPaperViewerViewController.swift
네비게이션 바 때문에 view.safeAreaIset.top이 0이됨으로 window의 safeArea를 참쪼
=> 속지 추가 모달 높이 인셋 조절

Dayol-iOS/UI/Common/Draw/DYDrawTool.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController+Drawable.swift
=> 다이어리 편집화면 올가미 툴 연동

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/UI/DiaryPaperModal/PaperSelectModal/PaperSelectCollectionView.swift, Dayol-iOS/UI/DiaryPaperModal/PaperSelectModal/PaperSelectCollectionViewCell.swift, Dayol-iOS/UI/DiaryPaperModal/PaperSelectModal/PaperSelectHeaderView.swift, Dayol-iOS/UI/DiaryPaperModal/PaperSelectModal/ViewModel/PaperSelectModalViewModel.swift, Dayol-iOS/UI/DiaryPaperModal/ViewController/PaperModalViewController.swift
=> 파일 이름 수정 MonthlyPaper > PaperSelect

Dayol-iOS/UI/Common/DiaryCover/DairyView.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditCoverView.swift, Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift, Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController+CollectionView.swift, Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift
- 다이어리 커버 로커 잘리는 현상 수정 및 관련 클래스 내부 불필요한 주석 제거
- 메인 다이어리 리스트 애니메이션 자연스럽게 수정
=> 다이어리 리스트 씬 디테일 작업

Dayol-iOS/UI/Common/Draw/Drawable.swift, Dayol-iOS/UI/Common/Draw/DrawableViewController.swift, Dayol-iOS/UI/Common/Draw/DrawingContentView.swift, Dayol-iOS/UI/Common/Toast/DYToastView.swift, Dayol-iOS/UI/Common/View/ToolBarContent/TextField/DYFlexibleTextField.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift, Dayol-iOS/UI/DiaryPaper/Papers/DiaryPaperEditViewController.swift
- 텍스트필드 선택 후 탭 한 위치에 텍스트 필드 생성 기능 추가
- 툴바 텍스트 버튼 눌렀을 때 토스트 노출되도록 구현
=> 텍트스필드 선택 후 탭 한 위치에 텍스트필드 생성 기능 추가

Dayol-iOS/TestData/DYTestData.swift, Dayol-iOS/UI/Common/Draw/DrawingContentView.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditViewController.swift, Dayol-iOS/UI/DiaryPaper/Papers/DiaryPaperEditViewController.swift, Dayol-iOS/UI/DiaryPaper/Papers/PaperPresenterView/PaperPresentView.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Paper/DiaryPaperViewController.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Paper/DiaryPaperViewModel.swift
- 코어데이터 연동 전 DYTestData에 연동 작업 먼저 진행했습니다.
=> Paper 편집 내용 DYTestData 연동

Dayol-iOS/UI/Common/DiaryCover/DairyView.swift, Dayol-iOS/UI/DiaryEdit/View/DiaryEditCoverView.swift, Dayol-iOS/UI/Home/DiaryList/View/DiaryListCell.swift, Dayol-iOS/UI/Home/DiaryList/ViewController/DiaryListViewController.swift, Dayol-iOS/UI/Home/Favorite/FavoriteViewController.swift
=> 홈 다이어리 리스트, 다이어리 생성화면 해상도 대응

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/Data/CoreData/Dayol.xcdatamodeld/DayolModel.xcdatamodel/contents, Dayol-iOS/Data/Model/PaperScheldule.swift, Dayol-iOS/Extensions/Date+Extension.swift, Dayol-iOS/TestData/DYTestData.swift, Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/Model/MonthlyCalendarModel.swift, Dayol-iOS/UI/DiaryPaper/Papers/MonthlyCalendarView/ViewModel/MonthlyCalendarViewModel.swift, Dayol-iOS/UI/DiaryPaper/Papers/ScheduleView/ScheduleContrainerView.swift, Dayol-iOS/UI/DiaryPaper/Papers/ScheduleView/ScheduleViewModel.swift, Dayol-iOS/UI/DiaryPaper/Papers/WeeklyCalendarView/View/WeeklyCalendarView.swift, Dayol-iOS/UI/DiaryPaper/ViewController/Viewer/DiaryPaperViewerViewController.swift, Dayol-iOS/UI/DiaryPaperModal/Schedule/ContentSubviews/ScheduleDateDisplayView.swift, Dayol-iOS/UI/DiaryPaperModal/Schedule/ContentSubviews/ScheduleDateSelectView.swift, Dayol-iOS/UI/DiaryPaperModal/Schedule/ScheduleModalContentView.swift, Dayol-iOS/UI/DiaryPaperModal/Schedule/ViewModel/ScheduleModalViewModel.swift, Dayol-iOS/UI/DiaryPaperModal/ViewController/PaperModalViewController.swift
- schdule 관련 CRUD
- MonthlyPaper Model 분리
=> AddSchedule 사전작업

Dayol-iOS/Data/CoreData/Dayol.xcdatamodeld/DayolModel.xcdatamodel/contents, Dayol-iOS/Data/CoreData/Model/DecorationImageItemMO+CoreDataClass.swift, Dayol-iOS/Data/CoreData/Model/DecorationStickerItemMO+CoreDataClass.swift, Dayol-iOS/Data/CoreData/Model/DecorationTextFieldItemMO+CoreDataClass.swift, Dayol-iOS/Data/CoreData/PersistentManager.swift, Dayol-iOS/Data/Model/ContentsManager.swift, Dayol-iOS/Data/Model/DiaryManager.swift, Dayol-iOS/UI/Common/DYStickerView/DYImageSizeStretchableView.swift, Dayol-iOS/UI/Common/DYStickerView/DYStickerBaseView.swift, Dayol-iOS/UI/Common/DYStickerView/DYStickerSizeStretchableView.swift, Dayol-iOS/UI/Common/Draw/DrawingContentView.swift
유저 이미지, 커스텀 스티커 코어데이터 연동 작업 진행했습니다.
=> 커스텀(?) 스티커, 유저 이미지 스티커 코어데이터 연동

Dayol-iOS.xcodeproj/project.pbxproj, Dayol-iOS/AppDelegate.swift, Dayol-iOS/Config.swift, Dayol-iOS/Extensions/Dictionary+Extension.swift, Dayol-iOS/Extensions/Rxswift+Extension.swift, Dayol-iOS/Network/API/API.swift, Dayol-iOS/Network/API/IAP/GetMembershipReceipt.swift, Dayol-iOS/Network/API/IAP/MembershipReceiptAPI.swift, Dayol-iOS/Network/IAP/IAPManager.swift, Dayol-iOS/UI/Base.lproj/LaunchScreen.storyboard, Dayol-iOS/UI/Common/DYViewContoller/DYViewController.swift, Dayol-iOS/UI/Launch/LaunchManager.swift, Dayol-iOS/UI/Launch/LaunchViewController.swift, Dayol-iOS/UI/Launch/Onboarding/OnboardingContentView.swift, Dayol-iOS/UI/Launch/Onboarding/OnboardingView.swift, Dayol-iOS/UI/Membership/MemberShipViewController.swift, Dayol-iOS/Utils/Logging.swift
=> 영수증 검증 및 API 모듈 구현
